### Multi Classification

In [1]:
import tensorflow as tf
import numpy as np
tf.random.set_seed(5)

In [2]:
# 학습 데이터

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_train = np.array(x_data, dtype = np.float32)
y_train = np.array(y_data, dtype = np.float32)
print(x_train.shape, y_train.shape)

(8, 4) (8, 3)


In [3]:
# 변수 초기화

nb_classes = 3

W = tf.Variable(tf.random.normal([4, nb_classes]), name = 'weight')
b = tf.Variable(tf.random.normal([nb_classes]), name = 'bias')
print(W)
print(b)

Metal device set to: Apple M2
<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[-0.18030666, -0.95028627, -0.03964049],
       [-0.7425406 ,  1.3231523 , -0.61854804],
       [ 0.8540664 , -0.08899953,  2.4488697 ],
       [ 0.762508  ,  1.2659615 ,  0.9801489 ]], dtype=float32)>
<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0.22652863, 0.8106553 , 0.7466094 ], dtype=float32)>


2023-07-13 00:26:21.223976: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-07-13 00:26:21.224055: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [4]:
# 예측 함수

def logits(X):
    return tf.matmul(X, W) + b

def hypothesis(X):
    return tf.nn.softmax(logits(X))

In [5]:
# 비용 함수

def cost_func():
    cost_i = tf.nn.softmax_cross_entropy_with_logits(logits = logits(x_train), labels = y_train)
    cost = tf.reduce_mean(cost_i)
    return cost

In [6]:
# 경사 하강법

optimizer = tf.keras.optimizers.Adam(learning_rate = 0.01)

In [7]:
# 학습

print('***** Start Learning!!')
for step in range(5001):
    optimizer.minimize(cost_func, var_list=[W, b])
    if step % 1000 == 0:
        print('%04d'%step, 'cost:[', cost_func().numpy(), ']',
             ' W:', W.numpy(), ' b:', b.numpy())
print('***** Learning Finished!!')

***** Start Learning!!
0000 cost:[ 5.9294786 ]  W: [[-0.17030679 -0.94028634 -0.04964045]
 [-0.7325406   1.3331522  -0.628548  ]
 [ 0.86406636 -0.07899956  2.4388697 ]
 [ 0.77250797  1.2759615   0.9701489 ]]  b: [0.2365285  0.8206551  0.73660946]
1000 cost:[ 0.31467563 ]  W: [[-2.2194254e+00  5.2480650e-01  1.1872520e+00]
 [ 1.2104942e-01  2.2536039e-03 -6.3699313e-02]
 [ 2.2870748e+00  1.1651013e+00  6.7434859e-01]
 [ 1.2760859e+00  1.7768891e+00  3.7673828e-01]]  b: [-2.718771  -1.5067654  4.317268 ]
2000 cost:[ 0.16304676 ]  W: [[-3.7972474   1.3537486   2.2676601 ]
 [ 0.04149157  0.02373841  0.06498635]
 [ 3.5885103   1.0490643  -0.50220144]
 [ 1.0556872   1.8170295   0.5562783 ]]  b: [-6.115446  -1.3375328  7.1691628]
3000 cost:[ 0.089659505 ]  W: [[-5.234307    2.1662514   3.2086892 ]
 [-0.04390961  0.06965949  0.16019607]
 [ 4.872837    0.6919886  -1.5755098 ]
 [ 0.73720884  2.0572226   0.74264306]]  b: [-9.075827  -1.3604153  9.762425 ]
4000 cost:[ 0.05118679 ]  W: [[-6.569139 

In [8]:
# Weight & Bias

print('Weight:', W.numpy())
print('Bias:', b.numpy())

Weight: [[-7.8441896e+00  3.6925631e+00  4.8953695e+00]
 [-2.1366227e-01  1.7167942e-01  3.2927954e-01]
 [ 7.3285379e+00 -1.4590268e-01 -3.5808456e+00]
 [-2.5797891e-03  2.6041093e+00  1.1803550e+00]]
Bias: [-14.22404    -1.3462164  14.310631 ]


In [9]:
# 학습 데이터를 검증 데이터로 동일하게 사용하는 경우

x_test = x_train
y_test = y_train

In [10]:
# 예측

def predict(X):
    return tf.argmax(hypothesis(X), axis = 1)
preds = predict(x_test)

print(preds.numpy())
print(hypothesis(x_test).numpy())
print(tf.argmax(y_test, axis = 1).numpy())

[2 2 2 1 1 1 0 0]
[[6.72011165e-15 4.47877028e-06 9.99995470e-01]
 [3.08857696e-11 6.25734450e-03 9.93742645e-01]
 [8.28591700e-18 3.15836854e-02 9.68416333e-01]
 [5.72436142e-16 9.75103438e-01 2.48965956e-02]
 [5.86906783e-02 9.39635932e-01 1.67340611e-03]
 [3.06679886e-02 9.69142973e-01 1.89006110e-04]
 [9.22718585e-01 7.72805959e-02 9.12350174e-07]
 [9.99054015e-01 9.46026354e-04 1.01469264e-10]]
[2 2 2 1 1 1 0 0]
