### XOR Problem

In [1]:
import tensorflow as tf
import numpy as np
tf.random.set_seed(5)

In [2]:
# 학습 데이터

x_data = [[0, 0],
          [0, 1],
          [1, 0],
          [1, 1]]
y_data = [[0],
          [1],
          [1],
          [0]]

x_train = np.array(x_data,dtype=np.float32)
y_train = np.array(y_data,dtype=np.float32)
print(x_train.shape, y_train.shape)

(4, 2) (4, 1)


In [3]:
# Layer 1: 은닉층(Hidden Layer)

# (4,2) * (2,2) = (4,2)
W1 = tf.Variable(tf.random.normal([2, 2]), name = 'weight1')
b1 = tf.Variable(tf.random.normal([2]), name = 'bias1')

def layer1(X):
    return tf.sigmoid(tf.matmul(X,W1) + b1)  

Metal device set to: Apple M2


2023-07-13 00:40:53.801015: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-07-13 00:40:53.801092: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [4]:
# Layer 2: 출력층(Output Layer)

# (4,2) * (2,1) = (4,1)
W2 = tf.Variable(tf.random.normal([2, 1]), name = 'weight2')
b2 = tf.Variable(tf.random.normal([1]), name = 'bias2')

In [5]:
# 예측 함수

def hypothesis(X):
    return tf.sigmoid(tf.matmul(layer1(X), W2) + b2)

In [6]:
# 비용 함수

def cost_func():
    cost = -tf.reduce_mean(y_train*tf.math.log(hypothesis(x_train)) +
                          (1 - y_train)*tf.math.log(1 - hypothesis(x_train)))
    return cost

In [7]:
# 경사 하강법

optimizer = tf.keras.optimizers.Adam(learning_rate = 0.01)

In [8]:
# 학습

print('***** Start Learning!!')
for step in range(10001):
    optimizer.minimize(cost_func, var_list = [W1, b1, W2, b2])
    if step % 1000 == 0:
        print('%04d'%step, 'cost:[', cost_func().numpy(), ']')
print('***** Learning Finished!!') 

***** Start Learning!!
0000 cost:[ 0.70409703 ]
1000 cost:[ 0.025501736 ]
2000 cost:[ 0.0068961554 ]
3000 cost:[ 0.0029871408 ]
4000 cost:[ 0.0015255288 ]
5000 cost:[ 0.00084185496 ]
6000 cost:[ 0.0004841077 ]
7000 cost:[ 0.0002849362 ]
8000 cost:[ 0.000170007 ]
9000 cost:[ 0.000102227226 ]
10000 cost:[ 6.1767234e-05 ]
***** Learning Finished!!


In [9]:
# Weight & Bias

print('Weight1:', W1.numpy())
print('Bias1:', b1.numpy())
print('Weight2:', W2.numpy())
print('Bias2:', b2.numpy())

Weight1: [[-8.268194 -9.911603]
 [-8.246879 -9.754799]]
Bias1: [12.438094  4.613185]
Weight2: [[ 20.246387]
 [-19.894123]]
Bias2: [-10.0956745]


In [10]:
# 학습 데이터를 그대로 검증 데이터로 사용하여 예측한 경우

x_test = x_train
y_test = y_train

In [11]:
# 예측

def predict(X):
    return tf.cast(hypothesis(X) > 0.5, dtype = tf.float32)
preds = predict(x_test)   
print(preds)

tf.Tensor(
[[0.]
 [1.]
 [1.]
 [0.]], shape=(4, 1), dtype=float32)


In [12]:
# 정확도

accuracy = tf.reduce_mean(tf.cast(tf.equal(preds,y_test), dtype = tf.float32))
print('Accuracy:', accuracy.numpy())
print('Hypothesis:\n', hypothesis(x_test).numpy())
print('Predict:\n', preds.numpy())

Accuracy: 1.0
Hypothesis:
 [[7.1333248e-05]
 [9.9994075e-01]
 [9.9994135e-01]
 [5.7823661e-05]]
Predict:
 [[0.]
 [1.]
 [1.]
 [0.]]
